data:extend{
	{ type = "int-setting", name = "barrel-size-stack",
		order = "b",
		setting_type = "startup",
		default_value = 10,
		minimum_value = 1,
--		allowed_values = {1,5,10,20,50,100,200,500,1000},
	},
	{ type = "int-setting", name = "barrel-size-capacity",
		order = "b",
		setting_type = "startup",
		default_value = 50,
		minimum_value = 1,
--		allowed_values = {1,5,10,20,50,100,200,500,1000},
	},
	{ type = "double-setting", name = "barrel-size-fill-time",
		order = "c",
		setting_type = "startup",
		default_value = .2,
		minimum_value = .002,
	},
}